title: Vladimir Bondar
url: "https://vladbondar.com"
# baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://vladbondar.com"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "VladimirBondarCV.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Blog"
   link: "https://blog.vladbondar.com"